### ISSUE TITLE
example of iframe 

### ISSUE THREAD

**Issue by fbgameresearch** [mozilla/django-csp#103]
can someone please add an example of iframe in a template pointing to yahoo.com or google.com

I want to add an iframe in my django template, pointing to an external application or website, and I am having hard time using django-csp , setting all its headers.

**Comment by g-k** [comment]
@fbgameresearch What do the settings.py and django template for your app look like?

In general you won't be able to iframe yahoo or google since they send x-frame-options or CSP headers to prevent clickjacking.

**Comment by g-k** [comment]
Closing this since it's pretty old at this point, but feel free to reopen if you're still running into problems.
