### ISSUE TITLE
`script-src-attr`, `script-src-elem`, `style-src-attr`, `style-src-elem` directives

### ISSUE THREAD

**Issue by jroblak** [mozilla/django-csp#108]
Are there plans to support these CSP header directives? I'm getting a lot of reports from Chrome browsers.

**Comment by EnTeQuAk** [comment]
I'd be happy to but currently, I don't have much time to read the spec and look into all of them to implement it. I'm very happy to review and mentor pull requests though!

**Comment by cedeber** [comment]
I would like to add some more (preload and prefetch). I can take care of them but I am quite new to the Python/Django world. I quickly check the code and it looks like that the only thing that needs to be done is around here:
https://github.com/mozilla/django-csp/blob/cf017a85127a1659291519c450afd82782409bec/csp/utils.py#L16

Am I right? Thanks.

**Comment by g-k** [comment]
@cedeber Yep! That's should be the only src code to update. We'll also want tests and docs as in https://github.com/mozilla/django-csp/pull/74/files

**Comment by darakian** [comment]
Made a PR https://github.com/mozilla/django-csp/pull/112

**Comment by darakian** [comment]
The CI system may be having an issue. My PR fails to build with issues like
```
pypy3 is not installed; attempting download
Downloading archive: https://language-archives.travis-ci.com/pypy3/binaries/ubuntu/14.04/x86_64/pypy3.tar.bz2
0.05s$ curl -sSf -o pypy3.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 403 Forbidden
Unable to download pypy3 archive. The archive may not exist. Please consider a different version.
```

**Comment by g-k** [comment]
Fixed in https://github.com/mozilla/django-csp/pull/112
