### ISSUE TITLE
Nonce blank when template rendered

### ISSUE THREAD

**Issue by ceiphr** [mozilla/django-csp#122]
When I render templates such as `base.html` and `index.html` in my template folder `nonce="{{request.csp_nonce}}"` works correctly.

When I render templates such as `js.html` and `css.html` in my pipeline subfolder inside my templates folder `nonce="{{request.csp_nonce}}"` produces `nonce=""`. 

`js.html` and `css.html` both override templates used by [django-pipeline](https://github.com/jazzband/django-pipeline). I'm not sure what to do to get nonce working with these files, but Firefox complains if any scripts don't contain nonce even if they come from `'self'`.

**Comment by darakian** [comment]
Have you included 
```
CSP_INCLUDE_NONCE_IN = [
    'script-src',
]
```
In your `django settings.py` file?

**Comment by ceiphr** [comment]
Correct, at this point I've abandoned trying to implement Nonce with my CSP, so I'm going to resolve the issue. Thank you for responding.

**Comment by FirefighterBlu3** [comment]
Multiple versions of Django from 2.2.7 to 3.0.4, multiple versions of django-csp from 3.3 up to 3.6.
I'd like to revisit this. My base.html template shows odd results. Note that there are two problems here; the documentation indicates that `{{nonce}}` is useable but it isn't unless `csp/context_processors.py` adds `'nonce'` to the dictionary.

```python
CSP_INCLUDE_NONCE_IN = ['default-src', 'script-src', 'style-src']
CSP_FOO...=...

MIDDLEWARE = [
    ...
    'csp.middleware.CSPMiddleware',
]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'csp.context_processors.nonce',
            ],
        },
    },
]
```

a snippet of my base.html (with `'nonce'` added to `csp/context_processors.py`)
```html
  <script
    src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
    crossorigin="anonymous"
    nonce="{{request.csp_nonce}}"
    nunce="{{request.csp_nonce}}"
    nance="{{CSP_NONCE}}"
    nence="{{nonce}}"></script>
```

Regardless of other issues, if `nonce=<anything at all>`, the HTML received by the browser is equal to `'... nonce ...'`, not `"... nonce=""` or `... nonce=foo` etc, just empty. e.g. if `base.html` is edited to say `nonce=abc123`, the HTML that arrives at the browser becomes `... nonce `. As a result, it doesn't matter what static value or `"{{variable}}"` is used. If the keyword `nonce=` is used the assignment value for that keyword is emptied.

the generated HTML is:
```html
<script src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" 
  crossorigin="anonymous"
  nonce
  nunce="giqSNjTinQJxMQov"
  nance="giqSNjTinQJxMQov"
  nence="giqSNjTinQJxMQov"></script>
```

I haven't dug this deep into Django template handling before so advice is welcome, particularly, where does the template string of nonce={{foo}} actually get changed to nonce=value? If i edit `csp/middleware.py` and print `response.content` before the return, the value is correct. e.g.
```html
... crossorigin="anonymous" nonce="abc123" nunce="VGJnrG3IT3iPifm8" nance="VGJnrG3IT3iPifm8" 
```

and also correct if `nonce="{{CSP_NONCE}}"` is used.

This just doesn't make it the rest of the way through Django on its way to the browser.

**Comment by darakian** [comment]
I wish I had an answer for you, but I think something in your django pipe is removing the nonce values. I had a similar issue with another middleware where the variable `{{request.csp_nonce}}` was being rendered by that middleware (poorly at that).

If feasible can you remove elements from the pipeline one by one to check?

**Comment by FirefighterBlu3** [comment]
after a lot of research, it's actually working but appears to not be. it is an intentional thing by Chrome -- https://stackoverflow.com/questions/55670985/google-chrome-stripping-nonce-values-from-script-tags 

i've verified this by using curl, the nonce value is actually there. now why Chrome is complaining in the console that there's no nonce as required by CSP, that's another mystery to solve.

**Comment by darakian** [comment]
Oh interesting. Thank you for the update that's fascinating! Perhaps the complaint is a bug in chrome then :)

**Comment by FirefighterBlu3** [comment]
It's part of the specification but few browsers implement it as intended

**Comment by g-k** [comment]
Huh that's confusing web platform behavior, we should definitely mention it in the docs.

**Comment by DylanYoung** [comment]
Should this issue be closed again?
