### ISSUE TITLE
Documentation Request: CSP_INCLUDE_NONCE_IN

### ISSUE THREAD

**Issue by darakian** [mozilla/django-csp#123]
Currently it's unclear if I need to add anything to my templating in order to have a nonce delivered on my scripts. I've been toying with the option and an example would be very nice to work off of.

**Comment by idlesign** [comment]
Example for Firefox handling `nonce-` in `<script>`:

```
CSP_INCLUDE_NONCE_IN = [
    'default-src',
    'script-src',
]
```

**Comment by darakian** [comment]
Should the nonce be viewable via the rendered html source?
