### ISSUE TITLE
Add support for Django 3.0

### ISSUE THREAD

**Issue by archatas** [mozilla/django-csp#129]
When do you plan to release the next version with the support for Django 3.0? It seems that the version at the master already has the updates necessary compared to the unsupported version 3.5.

**Comment by g-k** [comment]
Good question! I just updated our CI jobs to test 3.0.x, but don't have release rights on pypi.

django-csp 3.5 went out Jan. 16th 2019, but we haven't released the import fix: https://github.com/mozilla/django-csp/compare/3.5..master

@pmac or @EnTeQuAk can you cut a release?

**Comment by bartTC** [comment]
I would like to raise my hands as well. Currently I have to use the Github master branch for Django 3.0 (works fine).

Please make a pypi release.

**Comment by pmac** [comment]
I'll see what I can do. I haven't maintained this project for a while, but it does seem I still have permissions on PyPI. Apologies for the delay.

**Comment by dmptrluke** [comment]
I would appreciate a release too!

**Comment by Svetlitski** [comment]
Would also appreciate this!

**Comment by kostya-ten** [comment]
+1

**Comment by EnTeQuAk** [comment]
Apologies for the delay again, I didn't actually manage to startup my laptop during the holidays. I'll plan to issue the release today, ideally in the next few hours.

**Comment by dmptrluke** [comment]
Thanks @EnTeQuAk, that's great news!

**Comment by EnTeQuAk** [comment]
The release just went out, https://pypi.org/project/django-csp/3.6/

Please do test and report any issues if you have some. Thanks a lot for bearing with us.
