### ISSUE TITLE
3.7 and 3.8 "pep8: FutureWarning: Possible nested set at position 1"

### ISSUE THREAD

**Issue by g-k** [mozilla/django-csp#137]
in 3.7 and 3.8 against django master:

```
3.7-master run-test: commands[4] | py.test --cov=/home/travis/build/mozilla/django-csp/csp /home/travis/build/mozilla/django-csp/csp

/home/travis/build/mozilla/django-csp/.tox/3.7-master/lib/python3.7/site-packages/pep8.py:99: FutureWarning: Possible nested set at position 1

  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
```

https://travis-ci.org/mozilla/django-csp/jobs/620263359
https://travis-ci.org/mozilla/django-csp/jobs/620263358

**Comment by DylanYoung** [comment]
Possibly an environment problem: https://github.com/PyCQA/pydocstyle/issues/345

???

**Comment by g-k** [comment]
Still occurring on 3.{8,9}-main: 

* https://app.circleci.com/pipelines/github/mozilla/django-csp/36/workflows/758209e6-b7e6-4898-bead-cdbd83fc38d7/jobs/807?invite=true#step-103-121
* https://app.circleci.com/pipelines/github/mozilla/django-csp/36/workflows/758209e6-b7e6-4898-bead-cdbd83fc38d7/jobs/809

Since it's clearly coming from pep8 I don't think we need to do anything in django-csp.

**Comment by DylanYoung** [comment]
@g-k   I was able to fix this by updating bunch of test dependencies.  Would you like me to push a branch for it?  It's on my #36 branch right now, but it'd be easy to pull out.

**Comment by DylanYoung** [comment]
Also encountered these this, which might be worth someone being aware of:

https://foss.heptapod.net/pypy/pypy/-/issues/3751
(More discussion here https://code.djangoproject.com/ticket/28358)
