### ISSUE TITLE
Docs are out of date on RTD

### ISSUE THREAD

**Issue by marksweb** [mozilla/django-csp#143]
I forked the repo & was about to make changes to the docs because various settings aren't listed;
https://django-csp.readthedocs.io/en/latest/configuration.html

Examples of missing settings;

### CSP_SCRIPT_SRC_ATTR
    Set the `script-src-attr` directive. A tuple or list.
### CSP_SCRIPT_SRC_ELEM
    Set the `script-src-elem` directive. A tuple or list.

I primarily noticed this because the docs updates in this commit are not present; https://github.com/mozilla/django-csp/commit/69176422ba1cf4db754de0aa13f303199b14c549

**Comment by davidfischer** [comment]
It looks like the GitHub webhook is no longer active on Read the Docs. The webhook can be reactivated using the steps here: https://docs.readthedocs.io/en/stable/webhooks.html

**Comment by g-k** [comment]
Thanks! This might be related to #63.

We are missing the webhooks for https://django-csp.readthedocs.io/en/latest/

@EnTeQuAk or @muffinresearch do you have access to the django-csp project on RTD? I don't.

I added webhooks for https://django-csp-test.readthedocs.io/en/latest/configuration.html in the interim

**Comment by muffinresearch** [comment]
> Thanks! This might be related to #63.
> 
> We are missing the webhooks for https://django-csp.readthedocs.io/en/latest/
> 
> @EnTeQuAk or @muffinresearch do you have access to the django-csp project on RTD? I don't.
> 
> I added webhooks for https://django-csp-test.readthedocs.io/en/latest/configuration.html in the interim

@g-k I have rtd access, but I don't have settings access to this repo, if you can give me the latter I should be able to fix this.

**Comment by muffinresearch** [comment]
Actually this looks to have fixed itself having re-saved the settings on the rtd side. https://django-csp.readthedocs.io/en/latest/

**Comment by g-k** [comment]
Great, thanks Stuart!

I see a RTD integration, but it looks like GH deprecated it. Not sure why perms changed, I'll check with GH owners about that.

**Comment by koto** [comment]
I think this no longer works, currently [readthedocs latest](https://django-csp.readthedocs.io/en/latest/index.html) is at 3.6.

**Comment by g-k** [comment]
https://django-csp-test.readthedocs.io/en/latest/ is on 3.7 in the interim

**Comment by g-k** [comment]
cc @muffinresearch re: getting the main RTD docs updated

**Comment by sgelis** [comment]
What's the status on this one? I got hit by outdated docs on RTD today :/

**Comment by oerd** [comment]
Having two RTD domains, especially where the most updated one has a `-test` on it, seems misleading at best. I even wondered if there might have been some takeover of sorts...

**Comment by some1ataplace** [comment]
Updating the documentation on Read The Docs for django-csp would involve updating the version of the documentation being hosted by Read The Docs. To do this, you can follow these steps:

1. Fork the django-csp repository.
2. Clone the forked repository to your local machine.
3. Create a new branch on your local machine to make changes to the documentation.
4. Update the documentation to reflect the changes made in version 3.7 of django-csp.
5. Commit the changes to the new branch on your local machine.
6. Push the new branch to your forked django-csp repository on GitHub.
7. Create a pull request to merge your changes into the upstream django-csp repository.
8. Once the pull request is merged, the updated documentation will be automatically built and hosted on Read The Docs.

As for the code, the only code change that needs to be made is in the readthedocs.yml file, which is responsible for building and deploying the documentation to Read The Docs. You can update the version number in that file to reflect the latest version of django-csp.

https://stackoverflow.com/questions/60364789/how-do-i-correctly-start-using-readthedocs-yml

https://docs.readthedocs.io/en/stable/config-file/v2.html

```
# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required version of the documentation
version: 2

# Build environment
# Note: If you're using a .env file to store your environment variables, add the .env file location in the "environment" section below
# Example: env: file://.env
# See https://docs.readthedocs.io/en/stable/config-file/v2.html#build-environment for details
build:
  image: latest

# Required Python version
python:
  version: 3.8

# Required Sphinx version
sphinx:
  version: 3.2.1

# Documentation versions
# Note: You can modify this section to include the versions of your documentation you want to build on Read the Docs
# See https://docs.readthedocs.io/en/stable/versions.html for details
docs:
  - latest

# Build commands
# See https://docs.read/thedocs.io/en/stable/config-file/v2.html#build-commands for details
build:
  # Use the Sphinx-build Makefile to build the documentation
  # Note: Replace "docs" with the name of your documentation folder if it's different from "docs"
  # See https://www.sphinx-doc.org/en/master/man/sphinx-build.html for details on Sphinx-build
  # See https://docs.readthedocs.io/en/stable/builds/sphinx.html for details on building Sphinx-based documentation on Read the Docs
  # Note: We're also using the "sphinx-intl" package to generate translated versions of the documentation
  # See https://docs.readthedocs.io/en/stable/builds/translations.html for details on building translated documentation
  # Note: This script also sets the CSP_HEADER default value in the Django settings
  # See https://django-csp.readthedocs.io/en/latest/configuration.html#setting-the-csp-header for more information
  # Note: Replace "django-csp" with the name of your project if it's different from "django-csp"
  sphinx:
    configuration: docs/conf.py
    build_command: 
      pip install pyttsx3
      sphinx-build -T -E -b html -d build/doctrees -D language=en_US docs build/html
      sphinx-build -T -E -b html -d build/doctrees -D language=es_MX docs build/html/es_MX
      sphinx-intl update -p build/gettext -l en_US
      sphinx-intl update -p build/gettext -l es_MX
      cd example_project && python manage.py migrate && python manage.py collectstatic --no-input
      cd .. && pytest
      python -c 'import django_csp; django_csp.settings.CSP_HEADER["default-src"] += ["https://example.com/"]' 
      sphinx-build -b html -D language=en doc/source doc/build/html &&
      sphinx-intl update -p doc/locales &&
      sphinx-intl build -d doc/build/locale &&
      sphinx-build -b html -D language=en doc/source doc/build/html &&
      cp -r doc/build/html/* /home/docs/checkouts/readthedocs.org/user_builds/django-csp/checkouts/latest/docs/_build/html/ &&
      echo "import django\nfrom django.conf import settings\nsettings.configure()" > /home/docs/checkouts/readthedocs.org/user_builds/django-csp/doc/requirements.txt &&
      echo "django-csp" >> /home/docs/checkouts/readthedocs.org/user_builds/django-csp/doc/requirements.txt &&
      echo "\n# Set the default CSP_HEADER value\nimport django_csp\nCSP_HEADER = getattr(settings, 'CSP_HEADER', getattr(django_csp, 'CSP_HEADER_DEFAULT', {}))\nsettings.CSP_HEADER = CSP_HEADER" >> /home/docs/checkouts/readthedocs.org/user_builds/django-csp/doc/requirements.txt

# Use the appropriate Python version for your project
  python:
    version: 3.9
  # Use the appropriate cache configuration for your project
  # See https://docs.readthedocs.io/en/stable/caching.html for details on cache
  cache:
    - pip
    - directories:
        - "~/.cache"


# Use the Sphinx documentation builder
sphinx:
  configuration: docs/source/conf.py

# Set the default version of your documentation
# See https://docs.readthedocs.io/en/stable/versions.html#default-branch-or-version for details
version: latest
```

Note that the example assumes you're using Sphinx as your documentation builder, so adjust the configuration if you're using something else.

**Comment by stevejalim** [comment]
FYI y'all, am trying to get the docs rebuilding now

**Comment by stevejalim** [comment]
Ok docs are manually building again (for main) which is functionally the same as 3.7

I'll look to get the webhook happy again for the django-csp subdomain and not django-csp-test

**Comment by stevejalim** [comment]
FYI automatic docs builds via the GH webhook are now happening again for django-csp.readthedocs.io

**Comment by stevejalim** [comment]
Both of the settings mentioned in @marksweb's original message are live on the RTD site, so I'm counting this as resolved now. 

Time to build some momentum!

**Comment by stevejalim** [comment]
@janbrasna Done! Thanks for the spot
