### ISSUE TITLE
Sitemap.xml and Django error pages

### ISSUE THREAD

**Issue by 9mido** [mozilla/django-csp#147]
I am generating my sitemap.xml file automatically with code and I am not sure how to allow the sitemap.xml file using this package. 

Also with any django error pages such as the 403 error page - "CSRF verification failed. Request aborted" I do not know how to allow CSP to show that error page. 

According to this link:
https://lab.wallarm.com/how-to-trick-csp-in-letting-you-run-whatever-you-want-73cb5ff428aa/

"All you need for an XSS attack is to open an iframe and pointed it at any path that doesn’t include a CSP header. It can be the standard favicon.ico, robots.txt, sitemap.xml, css/js, jpg or other files."

CSRF Page error:

[https://github.com/django/django/blob/1.4.2/django/views/csrf.py](https://github.com/django/django/blob/1.4.2/django/views/csrf.py)

Refused to apply inline style because it violates the following Content Security Policy directive: "style-src ...........

Console Points To:

```
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="robots" content="NONE,NOARCHIVE">
  <title>403 Forbidden</title>
  <style type="text/css">
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font:small sans-serif; background:#eee; color:#000; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; margin-bottom:.4em; }
    h1 span { font-size:60%; color:#666; font-weight:normal; }
    #info { background:#f6f6f6; }
    #info ul { margin: 0.5em 4em; }
    #info p, #summary p { padding-top:10px; }
    #summary { background: #ffc; }
    #explanation { background:#eee; border-bottom: 0px none; }
  </style>
</head>
<body>
<div id="summary">
  <h1>Forbidden <span>(403)</span></h1>
  <p>CSRF verification failed. Request aborted.</p>
```

Sitemap.xml errors:

Refused to apply inline style because it violates the following Content Security Policy directive: "style-src ...........
prepareWebKitXMLViewer@VM709:30(anonymous)@VM709:383

```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"> ........
"use strict";

var nodeParentPairs = [];
var tree;

function prepareWebKitXMLViewer()
{
    var html = createHTMLElement('html');
    var head = createHTMLElement('head');
    html.appendChild(head);
    var style = createHTMLElement('style');
    style.id = 'xml-viewer-style';
    head.appendChild(style);
    var body = createHTMLElement('body');
    html.appendChild(body);
    var sourceXML = createHTMLElement('div');
    sourceXML.id = 'webkit-xml-viewer-source-xml';
    body.appendChild(sourceXML);

    var child;
    while (child = document.firstChild) {
        document.removeChild(child);
        if (child.nodeType != Node.DOCUMENT_TYPE_NODE)
            sourceXML.appendChild(child);
    }
    document.appendChild(html);

    var header = createHTMLElement('div');
    body.appendChild(header);
    header.classList.add('header');
    var headerSpan = createHTMLElement('span');
    header.appendChild(headerSpan);
    headerSpan.textContent = "This XML file does not appear to have any style information " +
      "associated with it. The document tree is shown below.";
    header.appendChild(createHTMLElement('br'));

    tree = createHTMLElement('div');
    body.appendChild(tree);
    tree.classList.add('pretty-print');
    window.onload = sourceXMLLoaded;
}
```

Update:

There seems to be an issue with Chrome because Chrome generates CSS and Javascript for the sitemap.xml file and robots.txt file. On firefox, I did not get any CSP errors.

**Comment by g-k** [comment]
It's good that you're applying CSP to all responses! You can extract those JS and CSS snippets to separate files hosted on a trusted on script and style source domain or allow inline JS and CSS script and style sources if you're OK weakening your CSP policy a bit.

**Comment by 9mido** [comment]
@g-k It would be preferable not to weaken the CSP policy. Can you provide code examples of how to resolve this the other way you mentioned? 

Chrome even does this with robots.txt with the django-robots library.

**Comment by g-k** [comment]
https://developers.google.com/web/fundamentals/security/csp/#inline_code_is_considered_harmful has an example of moving inlined styles and js to separate files. Otherwise you need to add `unsafe-inline` to `script-src` and `style-src` for those pages. Good luck!
