### ISSUE TITLE
Content Security Policy check failure. Only CSP_INCLUDE_NONCE_IN works well

### ISSUE THREAD

**Issue by NDMann** [mozilla/django-csp#151]
I have a very strange issue.

Only **CSP_INCLUDE_NONCE_IN** works well. Nonce generates a new code every page refresh and this is really great!
Unfortunately, the rest of the rules fail when I when I check the page in: [](https://observatory.mozilla.org/)

The only way to get the A+ mark is to manually add all the rules in the html pages with the line 
`<meta http-equiv="Content-Security-Policy" content="..." />`

Is this a software issue or just a misconfiguration?
Any idea on how to solve?
Thanks a lot!

**Here are the hosting server software:**
- Apache Version 2.4.43
- MySQL Version 10.1.45-MariaDB
- Python Version 3.7.3
- Django Version 3.0.6
- Architecture x86_64
- Protocols http and https (with and without www)
- Ports: 80 and 443

**Here are my rules in Django**
```
CSP_DEFAULT_SRC = ("'none'", )
CSP_BASE_URI = ("'none'", )
CSP_CONNECT_SRC = ("'self'", )
CSP_FORM_ACTION = ("'self'", )
CSP_FONT_SRC = ("'self'", "fonts.gstatic.com", "https://cdnjs.cloudflare.com", )
CSP_FRAME_ANCESTORS = ("'none'", )
CSP_FRAME_SRC = ("'self'", "https://www.google.com/recaptcha/", )
CSP_IMG_SRC = ("'self'", "https://www.gstatic.com;", "https://www.google-analytics.com", "https://www.googletagmanager.com", )
CSP_OBJECT_SRC = ("'none'", )
CSP_SCRIPT_SRC = ("'self'", "https://apis.google.com", "https://www.google.com/recaptcha/", "https://www.gstatic.com/recaptcha/", "https://www.google-analytics.com", "https://ssl.google-analytics.com", "https://www.googletagmanager.com", "https://cdnjs.cloudflare.com", "https://stackpath.bootstrapcdn.com", )
CSP_STYLE_SRC = ("'self'", "https://fonts.googleapis.com", "https://www.google.com/recaptcha/", "https://www.gstatic.com/recaptcha/", "https://cdnjs.cloudflare.com", )
CSP_SANDBOX = ("'allow-same-origin'", "'allow-forms'", "'allow-scripts'", "'allow-popups'", )
CSP_INCLUDE_NONCE_IN = ['script-src']
```

**Here is ho my html page starts:**
```
{% load static %}
{% load i18n %}
{% load csp %}
<!DOCTYPE html>
<html lang="en">
<head>
...
...
```

**Comment by 9mido** [comment]
@NDMann 

Yes the nonce works except it is not 128 bits (see my issue).

I think you are facing a configuration issue. For example, you need to specify the actual .css or .js files at the end of those links. Google links are a bit different and do not have .js or .css files and instead have something like /css.

Your browser console should help you figure out what you need to put at the end of the links. 

CSP_FONT_SRC should be something like:
https://fonts.gstatic.com/s/roboto/
'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/webfonts/fa-brands-400.woff2',
'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/webfonts/fa-brands-400.woff',
'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/webfonts/fa-brands-400.ttf',
'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/webfonts/fa-brands-400.svg',
'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/webfonts/fa-brands-400.eot',

STYLE_SRC should be something like:
"'self'",
'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css',
'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css',
'https://fonts.googleapis.com/css',

**Comment by NDMann** [comment]
Thanks @9mido !
Unfortunately I think I have something different.
I was really happy with your suggestions and I tried immediately, but still the same issues from [https://observatory.mozilla.org](https://observatory.mozilla.org)

**Here are my new super easy lines in django settings (just for testing)**
```
CSP_DEFAULT_SRC = ("'none'", )
CSP_BASE_URI = ("'none'", )
CSP_OBJECT_SRC = ("'none'", )
CSP_CONNECT_SRC = ("'self'", )
CSP_FORM_ACTION = ("'self'", )
CSP_FONT_SRC = ("'self'", )
CSP_FRAME_SRC = ("'self'", )
CSP_IMG_SRC = ("'self'", )
CSP_SCRIPT_SRC = ("'self'", )
CSP_STYLE_SRC = ("'self'", )
CSP_INCLUDE_NONCE_IN = ['script-src']
```

**Result**

- The page load all external fonts, scripts and styles (and should not)
- observatory.mozilla.org still complains about all those `CSP_` lines (for the website, those configurations are just missing)
- if i use the same settings in index.html header `meta http-equiv="Content-Security-Policy"`, all works as expected.  External sources are blocked and no website complains.

It really seems that those lines are just ignoned by django. 
**Only `CSP_INCLUDE_NONCE_IN = ['script-src']` works absolutely well.**
So the basic settings about django-scp should be fine, but something should be missimg somewhere.
Maybe I have to include some more things.

**in .htaccess I have no special lines related to django-csp**
_Maybe I need something in the .htaccess file for django-csp?_

**In index.html I have in the very beginning:**
```
{% load static %}
{% load i18n %}
{% load csp %}
<!DOCTYPE html>
```

**Question:** 
is there a special tag I need to add to the webpage to include the CSP settings?
Maybe something in `<head>` that create the missed `meta http-equiv="Content-Security-Policy"`

**Here is part of my settings.py**

```
import os
from django.utils.translation import gettext_lazy as _

...

INSTALLED_APPS = [
   ...
    'csp',
]

MIDDLEWARE = [
    ...
    'csp.middleware.CSPMiddleware',
]

...

CSP_DEFAULT_SRC = ("'none'", )
CSP_BASE_URI = ("'none'", )
CSP_OBJECT_SRC = ("'none'", )
CSP_CONNECT_SRC = ("'self'", )
CSP_FORM_ACTION = ("'self'", )
CSP_FONT_SRC = ("'self'", )
CSP_FRAME_SRC = ("'self'", )
CSP_IMG_SRC = ("'self'", )
CSP_SCRIPT_SRC = ("'self'", )
CSP_STYLE_SRC = ("'self'", )
CSP_INCLUDE_NONCE_IN = ['script-src']

...

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
               ...
                'csp.context_processors.nonce',
            ],
        },
    },
]
```

**Comment by 9mido** [comment]
@NDMann 

Here is my configuration for Mozilla Observatory which is passing:

CSP_DEFAULT_SRC= ("'self'",)
CSP_BASE_URI = ("'self'",)
CSP_FORM_ACTION = ("'self'",)
CSP_INCLUDE_NONCE_IN=['script-src']
CSP_STYLE_SRC = ["'self'",
    'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css',
    'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css',
    'https://fonts.googleapis.com/css',

]
CSP_SCRIPT_SRC = ["'self'", 
    'https://code.jquery.com/jquery-3.4.1.slim.min.js',
    'https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js',
    'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js',
    'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js',
    'https://player.vimeo.com/api/player.js',
    'https://code.jquery.com/jquery-3.5.1.slim.min.js',
]

CSP_FONT_SRC = ["'self'", 
    'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/webfonts/fa-brands-400.woff2',
    'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/webfonts/fa-brands-400.woff',
    'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/webfonts/fa-brands-400.ttf',
    'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/webfonts/fa-brands-400.svg',
    'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/webfonts/fa-brands-400.eot',
    'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/webfonts/fa-regular-400.woff2',
    'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/webfonts/fa-regular-400.woff',
    'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/webfonts/fa-regular-400.ttf',
    'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/webfonts/fa-regular-400.svg',
    'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/webfonts/fa-regular-400.eot',
    'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/webfonts/fa-solid-900.woff2',
    'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/webfonts/fa-solid-900.woff',
    'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/webfonts/fa-solid-900.ttf',
    'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/webfonts/fa-solid-900.svg',
    'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/webfonts/fa-solid-900.eot',
    'https://fonts.gstatic.com/s/roboto/',
]

CSP_IMG_SRC = ["'self'", ]

CSP_FRAME_SRC = ['https://player.vimeo.com/', 'https://www.youtube-nocookie.com/', 'https://www.youtube.com/', 'https://js.stripe.com/', ]

CSP_FRAME_ANCESTORS = ['https://player.vimeo.com/', 'https://www.youtube-nocookie.com/', 'https://www.youtube.com/', 'https://js.stripe.com/', "'self'", ]


If you are using a domain or localhost maybe try this technique (used for admin pages as an example):

CSP_STYLE_SRC = [
    '127.0.0.1:8000/static/css/base.css',
    '127.0.0.1:8000/static/admin/css/responsive.css',
    '127.0.0.1:8000/static/admin/css/forms.css',
    '127.0.0.1:8000/static/admin/css/widgets.css',
    '127.0.0.1:8000/static/admin/css/changelists.css',
    '127.0.0.1:8000/static/admin/css/base.css',
    '127.0.0.1:8000/static/admin/css/fonts.css',
    '127.0.0.1:8000/static/admin/css/dashboard.css',
    '127.0.0.1:8000/static/admin/css/login.css',
]

CSP_SCRIPT_SRC = [
    '127.0.0.1:8000/admin/jsi18n/',
    '127.0.0.1:8000/static/admin/js/vendor/jquery/jquery.js',
    '127.0.0.1:8000/static/admin/js/jquery.init.js',
    '127.0.0.1:8000/static/admin/js/core.js',
    '127.0.0.1:8000/static/admin/js/admin/RelatedObjectLookups.js',
    '127.0.0.1:8000/static/admin/js/actions.js',
    '127.0.0.1:8000/static/admin/js/urlify.js',
    '127.0.0.1:8000/static/admin/js/prepopulate.js',
    '127.0.0.1:8000/static/admin/js/vendor/xregexp/xregexp.js',
    '127.0.0.1:8000/static/admin/js/inlines.js',
    '127.0.0.1:8000/static/admin/js/change_form.js',
    '127.0.0.1:8000/static/admin/js/prepopulate_init.js',
    '127.0.0.1:8000/static/admin/js/collapse.js',
    '127.0.0.1:8000/static/admin/js/SelectBox.js',
    '127.0.0.1:8000/static/admin/js/SelectFilter2.js',
    '127.0.0.1:8000/static/admin/js/calendar.js',
    '127.0.0.1:8000/static/admin/js/admin/DateTimeShortcuts.js',
]


I am not doing {% load csp %} at all. And I do not have 'csp.context_processors.nonce' inside TEMPLATES. 

Your Apache/Nginx might need to point to your static root files correctly. I can't really help you there. 

To answer your question, I do not have anything in <head> or meta tags for CSP to load anything. 

Hope this helps. Otherwise I am out of ideas and someone else may need to help you.

**Comment by NDMann** [comment]
Thanks @9mido !
I will try to implement like you did.
In case it will not work, I think it may be because of some customized protection in my hosting (I'm not working locally and I'm using 443 port), or a strange misconfiguration somewhere else.
If your way to setup will also fail to me (and it's not so different), I'll use manually without using  external packages. Quite easy in this situation: nonce implemantation inside view.py and CSP implementation instde .htaccess and meta http-equiv="Content-Security-Policy"
Thanks really a lot for your time!!!

**Comment by g-k** [comment]
Sounds like this is resolved.
