### ISSUE TITLE
Maintaining config from Django Admin

### ISSUE THREAD

**Issue by jbothma** [mozilla/django-csp#153]
I'd like to use something like [django-csp-admin](https://github.com/AzMoo/django-csp-admin/) but it [makes an assumption about setting response._csp_config](https://github.com/AzMoo/django-csp-admin/blob/master/csp_admin/middleware.py#L21) and is a bit out of date

- is it ok for something outside django-csp to be modifying it? I don't see it in the docs
- would this feature be wanted inside django-csp or does it make sense as an add-on?  

My use case is that I want the security, but I want to allow editors to embed stuff. When they embed stuff that don't work, they should be able to ask a webmaster to allow more things in CSP without needing to re-deploy a django app with code changes.

**Comment by g-k** [comment]
Can `django-csp-admin` subclass `CSPMiddleware` and use its `build_policy` method? `build_policy` should be more stable than `_csp_config`


> is it ok for something outside django-csp to be modifying it? I don't see it in the docs

We can't guarantee the existence or stability of the attribute, so you'd need to vendor or pin the specific django-csp version you want to use with it.

https://stackoverflow.com/questions/8689964/why-do-some-functions-have-underscores-before-and-after-the-function-name/8689983#8689983

> would this feature be wanted inside django-csp or does it make sense as an add-on?

It does make sense to include in django-csp (e.g. if we can upstream django-csp). That said, we don't have the bandwidth to review and it keep up to date right now, so it's best left in a separate package.

**Comment by jbothma** [comment]
Thanks for the middleware subclass suggestion. That makes a lot of sense.

Thanks for the thorough response.
