### ISSUE TITLE
Vulnerability How To Trick CSP

### ISSUE THREAD

**Issue by 9mido** [mozilla/django-csp#159]
https://lab.wallarm.com/how-to-trick-csp-in-letting-you-run-whatever-you-want-73cb5ff428aa/

Not sure if this package currently is protected from such a vulnerability. If protected, then feel free to close this issue. Otherwise interesting read regardless. I did not test this vulnerability out myself and am not sure how to code a fix but maybe someone else could!

Here are some more possible ways that I did not test:

https://www.slideshare.net/Hacken_Ecosystem/ebrahem-hegazy-bug-hunters-manual-for-bypassing-contentsecuritypolicy

**Comment by g-k** [comment]
django-csp adds the CSP header. It doesn't guarantee that the site is using a secure CSP policy or adding the header to all responses. I can reopen this if there's a specific vulnerability you have in mind or insecure defaults you think we should change.
