### ISSUE TITLE
Middleware order

### ISSUE THREAD

**Issue by Jesus805** [mozilla/django-csp#162]
I followed the [tutorial](https://django-csp.readthedocs.io/en/latest/installation.html) to install django-csp, I'm not sure if I have the order correct.
```
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware', # <-- here
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
```
In Django, ordering is important for some Middleware [[1](https://docs.djangoproject.com/en/3.1/ref/middleware/#middleware-ordering)]. Does it matter at which row I place CSPMiddleware at?

I think it would be beneficial to state it in the installation webpage.

**Comment by g-k** [comment]
Hi, it should not matter unless you have other middleware modifying the CSP header. Feel free to submit a PR updating the docs.
