### ISSUE TITLE
Documentation needs to be updated to mention INSTALLED_APPS

### ISSUE THREAD

**Issue by Flimm** [mozilla/django-csp#168]
Look at this code in a Django template:

```
{% load csp %}
{% script %}
<script>
// ...
</script>
{% endscript %}
```

This won't work unless `csp` has been added to `INSTALLED_APPS`:

```
INSTALLED_APPS = [
    # ...
    'csp',
]
```

But the documentation doesn't mention anywhere that you need to add `csp` to `INSTALLED_APPS`.

**Comment by 9mido** [comment]
I did not have to add csp to INSTALLED_APPS. All I needed to do was add 'csp.middleware.CSPMiddleware' to MIDDLEWARE.

**Comment by flaiming** [comment]
I just had exact same problem. The documentation should be updated.

**Comment by Flimm** [comment]
This issue has been closed by somebody, and I can't re-open it. So I guess the right move here would be to create a new issue in this GitHub repo.
