### ISSUE TITLE
broken admin filters

### ISSUE THREAD

**Issue by rmmineiro** [mozilla/django-csp#173]
Adding CSP_INCLUDE_NONCE_IN=['script-src'] broke some of my admin filters (i.e. the ones subclassed from admin.filters.SimpleListFilter). I am on python 3.8.10 and django 3.2.3.  Does anyone have a simple work around this?

**Comment by silentsokolov** [comment]
Add log from browser's js-console

**Comment by rmmineiro** [comment]
The offending script is at the top of the markup

`<script type="text/javascript">var go_from_select = function(opt) { window.location = window.location.pathname + opt };</script>
<h3> By Concelho </h3>
<ul class="admin-filter-Concelho">

    <li>
    <select class="form-control" style="width: 95%;margin-left: 2%;"
        onchange="go_from_select(this.options[this.selectedIndex].value)">
    
        <option selected="selected"
         value="?">All</option>
    
        <option
         value="?concelho=Alcanena">Alcanena</option>
    
        <option
         value="?concelho=Entroncamento">Entroncamento</option>
    
        <option
         value="?concelho=Goleg%C3%A3">Golegã</option>
    
        <option
         value="?concelho=Tomar">Tomar</option>
    
        <option
         value="?concelho=Torres+Novas">Torres Novas</option>
    
    </select>
    </li>

</ul>`

I am thinking, override the template to insert the nonce. In that case, the remaining question is, which template?

**Comment by rmmineiro** [comment]
@silentsokolov looking at it further I think I will exclude admin prefixes and just use the front door :)
