### ISSUE TITLE
`CSP_INCLUDE_NONCE_IN` not working?

### ISSUE THREAD

**Issue by javulticat** [mozilla/django-csp#182]
I've been unable to get a nonce included in the CSP header generated by `django-csp`.  I've followed the instructions in the docs, and everything else seems to be working - other than getting a nonce to show up in the CSP header sent in my responses.

My `settings.py`:

```python
MIDDLEWARE = [
    # ...,
    "csp.middleware.CSPMiddleware",
]
CSP_DEFAULT_SRC = ["foo", "bar", "'self'"]
CSP_INCLUDE_NONCE_IN = ["default-src"]
```

Header: `Content-Security-Policy: default-src foo bar 'self'`

I'd expect something like: `Content-Security-Policy: default-src foo bar 'self' nonce-h893hjkfhdsu9hf8fd8a773hda`

Am I doing something wrong or looking in the wrong place?  Thanks!

**Comment by javulticat** [comment]
To anyone who runs into this issue: clearing cookies (or using incognito mode) fixed the issue.

**Comment by sgelis** [comment]
Thanks for opening this issue. Was hit with the exact same one today.

**Comment by DylanYoung** [comment]
Took a stab at a PR here.  

I wonder if it makes sense to change this behaviour slightly though as it seems somewhat unsafe.   If the nonce isn't used and it's not going to be included in the header, shouldn't the source list be set to 'none'?
