### ISSUE TITLE
Documentation for context processor

### ISSUE THREAD

**Issue by sagejason** [mozilla/django-csp#194]
Small update for the context_processor docs.

The [documentation](https://django-csp.readthedocs.io/en/latest/nonce.html ) says to use the variable` {{nonce}}`, but that doesen't work. Reading the code it should be `{{CSP_NONCE}}`

**Comment by Anv3sh** [comment]
Tested this it works for {{CSP_NONCE}} and not for {{nonce}} as the `csp.context_processor.nonce` returns `{'CSP_NONCE' : nonce}`.

**Comment by Anv3sh** [comment]
checked the `nonce.rst` the changes are already done but aren't reflected on [ReadTheDocs](http://django-csp.readthedocs.org/).

**Comment by some1ataplace** [comment]
There is a problem with #143 that should be fixed first. The docs are currently not the most current version. Once they are updated to the newest version, then we should add this information you stated to the docs.

**Comment by stevejalim** [comment]
@Anv3sh Can you confirm that the relevant docs are now live on django-csp.readthedocs.io, please? If so, we can go ahead and close this.

**Comment by Anv3sh** [comment]
> @Anv3sh Can you confirm that the relevant docs are now live on django-csp.readthedocs.io, please? If so, we can go ahead and close this.

Yes the docs are live for this particular issue on [django-csp.readthedocs.io](https://django-csp.readthedocs.io/en/latest/nonce.html#context-processor):
![image](https://github.com/mozilla/django-csp/assets/51405870/95ebd2cb-53df-4374-bc12-31fe655341ab)
