### ISSUE TITLE
CSP 1.1 directives

### ISSUE THREAD

**Issue by jsocol** [mozilla/django-csp#39]
This may be a meta issue, but there are a number of new directives in the CSP 1.1 draft that need to be added.

**Comment by g-k** [comment]
[CSP 1.1](
https://www.w3.org/TR/2014/WD-CSP11-20140211/) directive support:

- [x]    3.2.5.1 base-uri
- [x]    3.2.5.2 child-src
- [x]    3.2.5.3 connect-src
- [x]    3.2.5.4 default-src
- [x]    3.2.5.5 font-src
- [x]    3.2.5.6 form-action
- [x]    3.2.5.7 frame-ancestors
- [x]    3.2.5.8 frame-src
- [x]    3.2.5.9 img-src
- [x]    3.2.5.10 media-src
- [x]    3.2.5.11 object-src
- [ ]    3.2.5.12 plugin-types
- [ ]    3.2.5.13 referrer (removed in favor of https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy)
- [ ]    3.2.5.14 reflected-xss (removed https://bugs.chromium.org/p/chromium/issues/detail?id=657737 in favor of https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection)
- [x]    3.2.5.15 report-uri
- [x]    3.2.5.16 sandbox
- [x]    3.2.5.17 script-src
- [x]    3.2.5.18 style-src
