### ISSUE TITLE
Fallback for CSP_EXCLUDE_URL_PREFIXES is hardcoded

### ISSUE THREAD

**Issue by kezabelle** [mozilla/django-csp#44]
The default value for [CSP_EXCLUDE_URL_PREFIXES](https://github.com/mozilla/django-csp/blob/97622fa565a85ac9492c51bd085757a7a95a9879/csp/middleware.py#L22) is currently hardcoded as `('/admin',)`

I think it would make more sense to to do something like:
```
prefixes = getattr(settings, 'CSP_EXCLUDE_URL_PREFIXES', None)
if prefixes is None:
    try:
        prefixes = (reverse('admin:index'),)
    except NoReverseMatch:
        prefixes = ()
```

As this guarantees that the path to the standard Django admin (which I'm assuming was the target for `/admin` in the first place) is correct if used, *and* doesn't allow any of [these words](http://www.onelook.com/?w=admin*&scwo=1&sswo=1) (and whatever variants one might use) to accidentally be CSP free because of no trailing slash (which the Django admin would provide, being conceptually a URL namespace)

**Comment by graingert** [comment]
this can be closed too

**Comment by EnTeQuAk** [comment]
Indeed, thanks for the hint @graingert :)
