### ISSUE TITLE
[tracker] Add support for CSP 2.0 

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/django-csp#50]
Currently django-csp is missing support for CSP 2.0 settings:

Here's an overview of the changes from level 1 https://www.w3.org/TR/CSP2/#changes-from-level-1

**Comment by g-k** [comment]
The directives added in CSP 2.0 are:

- [x] base-uri
- [x] child-src
- [x] form-action
- [x] frame-ancestors
- [x] plugin-types

All of which we support.  The other changes are to nonce support and report formats and how the browser handles CSP headers.
