### ISSUE TITLE
Add deprecation notice for frame-src

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/django-csp#56]
Relates to #50 

This needs to be done carefully because since support for child-src is only hitting in FF45 (according to MDN) running both `child-src` and `frame-src` will be needed for maximum compatibility.

**Comment by g-k** [comment]
I think we can close this.

1.2.2.1 on https://w3c.github.io/webappsec-csp/#changes-from-level-2 says frame-src was undeprecated.
