### ISSUE TITLE
Add support for referrer policy 

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/django-csp#57]
See https://w3c.github.io/webappsec-referrer-policy/

**Comment by g-k** [comment]
`Referrer-Policy` is a separate header now and not part of CSP.

https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-delivery

Chrome removed it: https://www.chromestatus.com/feature/5680800376815616
Firefox still lists it on: https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives#referrer

**Comment by g-k** [comment]
Closing and recommend using the header e.g. `Referrer-Policy: no-referrer` or meta tag e.g. `<meta name="referrer" content="origin">`.

https://blog.mozilla.org/security/2015/01/21/meta-referrer/
http://caniuse.com/#feat=referrer-policy
