### ISSUE TITLE
Docs version is not in-sync with the package version

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/django-csp#62]
It would be nice to make sure that releases always update the version in the docs to match.

**Comment by rixx** [comment]
This issue persists – docs list themselves at version 3.0, while 3.4 is currently out.

**Comment by EnTeQuAk** [comment]
I worked on trying to find out who has access to do that, I'll assign the issue again to me to start another round and see if I can finally fix this. Sorry for the wait!

**Comment by EnTeQuAk** [comment]
Now, this is fixed as well: https://django-csp.readthedocs.io/en/latest/ (may need a force-reload)
