### ISSUE TITLE
support report-to header and directive

### ISSUE THREAD

**Issue by g-k** [mozilla/django-csp#79]
https://www.w3.org/TR/CSP/#directive-report-to
http://wicg.github.io/reporting/#examples

Still in draft and not in caniuse yet: https://github.com/Fyrd/caniuse/issues/2375

This is a separate spec and might belong in a separate package.

A possible config format like the following could add the report-to header and `report-to=endpoint-1` to the CSP header:

```python
REPORT_ENDPOINTS = (
    { "url": "https://example.com/reports",
       "group": "endpoint-1",
       "max-age": 10886400 },
     { "url": "https://backup.com/reports",
     "group": "endpoint-1",
     "max-age": 10886400 }
)  # could also be set statically by in the reverse/proxy or webserver config

CSP_REPORT_TO =  "endpoint-1"
```

We'd also need to define how this behaves with respect to `CSP_REPORT_URI`.

**Comment by rspeed** [comment]
Is this still in draft? [MDN lists CSP's `report-uri` directive as deprecated](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-uri) in favor of `report-to`.

**Comment by g-k** [comment]
> Is this still in draft?

Yeah, the reporting API is still in draft http://wicg.github.io/reporting/

The bug for implementing this in Firefox is https://bugzilla.mozilla.org/show_bug.cgi?id=1391243 and for other browsers I don't see it in caniuse.

I'd recommend using `report-uri` for the foreseeable future.

**Comment by g-k** [comment]
Closing for now, but we should continue to track the spec and support `report-to` if it ships.

**Comment by g-k** [comment]
We have a pr for this in #124

**Comment by g-k** [comment]
Huh looks like the API is still in draft (at least on https://w3c.github.io/reporting/), but per the MDN data at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to#Browser_compatibility Chrome shipped it.

**Comment by g-k** [comment]
additional link: https://developers.google.com/web/updates/2018/09/reportingapi
