### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by mark-adams** [mozilla/django-csp#93]
Hi all,

We'd like to take advantage of some new functionality added to django-csp. Is there any way that you could create a new release since it seems like there have been numerous changes since the last release?

Thanks! :smile:

**Comment by ogonkov** [comment]
pip is going to deprecate installation by git url, so new version is highly deserable

**Comment by raiderrobert** [comment]
@ogonkov don't think that's accurate. pipenv is the way of the future, and it's continuing to support it: https://github.com/pypa/pipenv/issues/1393

**Comment by marcuspen** [comment]
Any update on this? We at [Sohonet](https://sohonet.com) would also appreciate a new release for the new features...

**Comment by techalchemy** [comment]
To clarify, we (at pipenv) are continuing to support `git+ssh://` style urls which are what is implicit when using `git+git@` style urls.  To further clarify, pipenv uses pip on the backend, though we are not going to be deprecating anything directly as we have a significantly patched version of the pip resolver from pip 9.

**Comment by EnTeQuAk** [comment]
Version 3.4 just got tagged and will hit npm in a few moments.
