### ISSUE TITLE
Code coverage through coveralls?

### ISSUE THREAD

**Issue by raiderrobert** [mozilla/django-csp#96]
Something I didn't add into my earlier [contribution](https://github.com/mozilla/django-csp/pull/94) was coveralls or some similar tool. But I forgot to raise the issue beforehand, so I'm doing it now.

I usually like to look at the code coverage of projects, but since this project lacks it, I was thinking about suggesting adding it. Thoughts?

**Comment by EnTeQuAk** [comment]
We should definitely add code coverage tests at some point. We should make sure we have reasonable test-coverage before doing that though.

**Comment by g-k** [comment]
I guess we just needed to enable it, so I did that https://coveralls.io/github/mozilla/django-csp and added the badge to the readme. :tada:
